version: '3.8'

services:
  db:
    image: mysql:8.3
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: web-shopping
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - rabbitnet

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - rabbitnet

volumes:
  db_data:

networks:
  rabbitnet:
