version: '3.8'

services:
  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: web-shopping
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/web-shopping
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234

volumes:
  db_data:
